name = "Overthrow minus 0.7.7"; //This name will be displayed only in game , specifically the expansion menu
picture = "logo_overthrow.paa"; //Location of your addon's icon
logo = "logo_overthrow.paa";
logoOver = "logo_overthrow.paa";
actionName = "Website";   //The name of the action
action = "https://github.com/lymem/Overthrow"; //The action , "Authors Website Link"
description = "Overthrow minus - Overthrow sans Ace Medical - Version 0.7.8"; // Addon Description
overview = "A Revolution Simulator for Arma 3";
author = "Lyme";
overviewPicture = "logo_overthrow.paa";
